const mongoose = require('mongoose');

const patientSchema = new mongoose.Schema({
  registrationType: String,
  date: String,
  time: String,
  PRnumber1: String,
  PRnumber2: String,
  prefix: String,
  name: String,
  fatherSpouse: String,
  sex: String,
  age: String,
  dob: String,
  maritalStatus: String,
  bloodGroup: String,
  address1: String,
  address2: String,
  location: String,
  city: String,
  state: String,
  country: String,
  religion: String,
  occupation: String,
  mobile: String,
  email: String,
  aadhar: String,
  abhaId: String,
  department: String,
  plan: String,
  pConsultant: String,
  sConsultant: String,
  secondaryDepartment: String,
  secondaryConsultant: String,
  package: String,
  referredBy: String,
  provisionalDiagnosis: String,
  isMLC: Boolean,
  billType: String,
  discount: String,
  discountReason: String,
  paymentMode: String,
  registrationCharge: String,
  totaldiscount: String,
  netAmount: String,
  cardNumber: String
});

module.exports = mongoose.model('Patient', patientSchema);
